/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'startingNumber' : bigint,
  'businessName' : string,
  'state' : string,
  'invoicePrefix' : string,
  'gstin' : string,
  'address' : string,
}
export interface Customer {
  'id' : bigint,
  'contactInfo' : [] | [string],
  'billingAddress' : string,
  'name' : string,
  'state' : string,
  'gstin' : [] | [string],
}
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'lineItems' : Array<LineItem>,
  'customerId' : bigint,
}
export type InvoiceStatus = { 'finalized' : null } |
  { 'draft' : null };
export interface Item {
  'id' : bigint,
  'hsnSac' : [] | [string],
  'name' : string,
  'description' : [] | [string],
  'unitPrice' : number,
  'defaultGstRate' : number,
}
export interface LineItem {
  'itemId' : bigint,
  'discount' : [] | [number],
  'quantity' : number,
  'unitPrice' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<
    [string, string, [] | [string], string, [] | [string]],
    Customer
  >,
  'addItem' : ActorMethod<
    [string, [] | [string], [] | [string], number, number],
    Item
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvoice' : ActorMethod<[bigint, Array<LineItem>], Invoice>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'editCustomer' : ActorMethod<
    [bigint, string, string, [] | [string], string, [] | [string]],
    undefined
  >,
  'editInvoice' : ActorMethod<
    [bigint, bigint, Array<LineItem>, InvoiceStatus],
    undefined
  >,
  'editItem' : ActorMethod<
    [bigint, string, [] | [string], [] | [string], number, number],
    undefined
  >,
  'finalizeInvoice' : ActorMethod<[bigint], undefined>,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getItem' : ActorMethod<[bigint], [] | [Item]>,
  'getItems' : ActorMethod<[], Array<Item>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];