/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Opt(IDL.Text),
  'billingAddress' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'gstin' : IDL.Opt(IDL.Text),
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'hsnSac' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'unitPrice' : IDL.Float64,
  'defaultGstRate' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineItem = IDL.Record({
  'itemId' : IDL.Nat,
  'discount' : IDL.Opt(IDL.Float64),
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
});
export const InvoiceStatus = IDL.Variant({
  'finalized' : IDL.Null,
  'draft' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(LineItem),
  'customerId' : IDL.Nat,
});
export const BusinessProfile = IDL.Record({
  'startingNumber' : IDL.Nat,
  'businessName' : IDL.Text,
  'state' : IDL.Text,
  'invoicePrefix' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [Customer],
      [],
    ),
  'addItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Float64,
      ],
      [Item],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvoice' : IDL.Func([IDL.Nat, IDL.Vec(LineItem)], [Invoice], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'editCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'editInvoice' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(LineItem), InvoiceStatus],
      [],
      [],
    ),
  'editItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'finalizeInvoice' : IDL.Func([IDL.Nat], [], []),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(Item)], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Opt(IDL.Text),
    'billingAddress' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'gstin' : IDL.Opt(IDL.Text),
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'hsnSac' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'unitPrice' : IDL.Float64,
    'defaultGstRate' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'itemId' : IDL.Nat,
    'discount' : IDL.Opt(IDL.Float64),
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
  });
  const InvoiceStatus = IDL.Variant({
    'finalized' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(LineItem),
    'customerId' : IDL.Nat,
  });
  const BusinessProfile = IDL.Record({
    'startingNumber' : IDL.Nat,
    'businessName' : IDL.Text,
    'state' : IDL.Text,
    'invoicePrefix' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [Customer],
        [],
      ),
    'addItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Float64,
        ],
        [Item],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvoice' : IDL.Func([IDL.Nat, IDL.Vec(LineItem)], [Invoice], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'editCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'editInvoice' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(LineItem), InvoiceStatus],
        [],
        [],
      ),
    'editItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'finalizeInvoice' : IDL.Func([IDL.Nat], [], []),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(Item)], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };