/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface SignUpRequest {
    password: string;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StatusEntry {
    status: string;
    periodLabel: string;
    filingDate?: string;
    returnType: ReturnType_;
}
export interface LineItem {
    itemId: bigint;
    discount?: number;
    quantity: number;
    unitPrice: number;
}
export interface InvoiceKPIs {
    draftInvoices: bigint;
    finalizedInvoices: bigint;
    totalInvoices: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CredentialResponse {
    role?: SystemRole;
    message: string;
    success: boolean;
}
export interface UserRecord {
    id: string;
    permissions: Permissions;
    principal?: Principal;
    deleted: boolean;
    createdAt: bigint;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    lastSignIn?: Time;
    updatedAt: bigint;
    accessExpiry?: Time;
    passwordHash: string;
    lastUsed?: Time;
}
export interface GSTError {
    code: bigint;
    message: string;
}
export interface Permissions {
    canUseGstValidation: boolean;
    canVerifyBank: boolean;
    canManageUsers: boolean;
    canViewReports: boolean;
    canFileReturns: boolean;
    canExportData: boolean;
    canVerifyPan: boolean;
}
export interface CreateUserRequest {
    password: string;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}
export interface BankingDetails {
    branch?: string;
    ifscCode: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UpdateUserRequest {
    permissions: Permissions;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}
export interface SignUpResponse {
    id: string;
    permissions: Permissions;
    createdAt: bigint;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    updatedAt: bigint;
    accessExpiry?: Time;
    lastUsed?: Time;
}
export interface GSTFilingStatus {
    natureOfBusiness?: string;
    tradeName?: string;
    period: string;
    cancellationDate?: string;
    principalPlaceOfBusiness?: string;
    isActive?: boolean;
    filingFrequencyDetails?: string;
    error?: GSTError;
    legalName?: string;
    statusEntries: Array<StatusEntry>;
    state?: string;
    gstin: string;
    taxpayerType?: string;
    address?: string;
    gstStatus?: string;
    filingFrequency: FilingFrequency;
    registrationDate?: string;
    returnType: ReturnType_;
}
export interface Invoice {
    id: bigint;
    status: InvoiceStatus;
    lineItems: Array<LineItem>;
    purchaseOrderNumber?: string;
    invoiceDate: string;
    invoiceNumber: string;
    invoiceType: InvoiceType;
    customerId: bigint;
}
export interface Customer {
    id: bigint;
    contactInfo?: string;
    billingAddress: string;
    name: string;
    state: string;
    gstin?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Item {
    id: bigint;
    hsnSac?: string;
    name: string;
    description?: string;
    unitPrice: number;
    defaultGstRate: number;
}
export interface BusinessProfile {
    bankingDetails?: BankingDetails;
    startingNumber: bigint;
    logo?: ExternalBlob;
    businessName: string;
    state: string;
    invoicePrefix: string;
    gstin: string;
    address: string;
}
export interface UnifiedUserInfo {
    userType: Variant_credential_principalOnly;
    deleted?: boolean;
    role?: SystemRole;
    email?: string;
    lastSignIn?: Time;
    accessExpiry?: Time;
    identifier: string;
    lastUsed?: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FilingFrequency {
    quarterly = "quarterly",
    monthly = "monthly"
}
export enum InvoiceStatus {
    cancelled = "cancelled",
    finalized = "finalized",
    draft = "draft"
}
export enum InvoiceType {
    transportation = "transportation",
    original = "original"
}
export enum ReturnType_ {
    gstr1 = "gstr1",
    gstr3b = "gstr3b"
}
export enum SystemRole {
    auditor = "auditor",
    superAdmin = "superAdmin",
    standard = "standard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_credential_principalOnly {
    credential = "credential",
    principalOnly = "principalOnly"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(name: string, billingAddress: string, gstin: string | null, state: string, contactInfo: string | null): Promise<Customer>;
    addItem(name: string, description: string | null, hsnSac: string | null, unitPrice: number, defaultGstRate: number): Promise<Item>;
    adminGetUserInvoiceKPIs(userId: string): Promise<InvoiceKPIs>;
    adminGetUserInvoices(userId: string): Promise<Array<Invoice>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateApplicationCredentials(userId: string, password: string): Promise<CredentialResponse>;
    cancelInvoice(id: bigint): Promise<void>;
    createInvoice(invoiceNumber: string, purchaseOrderNumber: string | null, customerId: bigint, lineItems: Array<LineItem>, invoiceDate: string, invoiceType: InvoiceType): Promise<Invoice>;
    createUser(request: CreateUserRequest): Promise<SignUpResponse>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteItem(id: bigint): Promise<void>;
    deleteUser(userId: string): Promise<void>;
    editCustomer(id: bigint, name: string, billingAddress: string, gstin: string | null, state: string, contactInfo: string | null): Promise<void>;
    editInvoice(id: bigint, invoiceNumber: string, purchaseOrderNumber: string | null, customerId: bigint, lineItems: Array<LineItem>, status: InvoiceStatus, invoiceDate: string, invoiceType: InvoiceType): Promise<void>;
    editItem(id: bigint, name: string, description: string | null, hsnSac: string | null, unitPrice: number, defaultGstRate: number): Promise<void>;
    fetchGstFilingStatus(gstin: string, period: string, returnType: ReturnType_, filingFrequency: FilingFrequency): Promise<GSTFilingStatus>;
    finalizeInvoice(id: bigint): Promise<void>;
    getAccessExpiry(userId: string): Promise<Time | null>;
    getBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomers(): Promise<Array<Customer>>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getInvoices(): Promise<Array<Invoice>>;
    getItem(id: bigint): Promise<Item | null>;
    getItems(): Promise<Array<Item>>;
    getLastSignIn(userId: string): Promise<Time | null>;
    getLastUsed(userId: string): Promise<Time | null>;
    getPotentialSystemRoles(): Promise<Array<SystemRole>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserProfile(): Promise<boolean>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<UnifiedUserInfo>>;
    listUsers(): Promise<Array<UserRecord>>;
    recordInternetIdentitySignIn(): Promise<void>;
    saveBusinessProfile(profile: BusinessProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAccessExpiry(userId: string, expiryTimestamp: Time | null): Promise<void>;
    signUp(request: SignUpRequest): Promise<SignUpResponse>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateUser(userId: string, request: UpdateUserRequest): Promise<void>;
}
import type { BankingDetails as _BankingDetails, BusinessProfile as _BusinessProfile, CreateUserRequest as _CreateUserRequest, CredentialResponse as _CredentialResponse, Customer as _Customer, ExternalBlob as _ExternalBlob, FilingFrequency as _FilingFrequency, GSTError as _GSTError, GSTFilingStatus as _GSTFilingStatus, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, InvoiceType as _InvoiceType, Item as _Item, LineItem as _LineItem, Permissions as _Permissions, ReturnType as _ReturnType, SignUpRequest as _SignUpRequest, SignUpResponse as _SignUpResponse, StatusEntry as _StatusEntry, SystemRole as _SystemRole, Time as _Time, UnifiedUserInfo as _UnifiedUserInfo, UpdateUserRequest as _UpdateUserRequest, UserProfile as _UserProfile, UserRecord as _UserRecord, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string | null): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Customer_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Customer_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addItem(arg0: string, arg1: string | null, arg2: string | null, arg3: number, arg4: number): Promise<Item> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Item_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Item_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserInvoiceKPIs(arg0: string): Promise<InvoiceKPIs> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserInvoiceKPIs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserInvoiceKPIs(arg0);
            return result;
        }
    }
    async adminGetUserInvoices(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserInvoices(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserInvoices(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateApplicationCredentials(arg0: string, arg1: string): Promise<CredentialResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateApplicationCredentials(arg0, arg1);
                return from_candid_CredentialResponse_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateApplicationCredentials(arg0, arg1);
            return from_candid_CredentialResponse_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelInvoice(arg0);
            return result;
        }
    }
    async createInvoice(arg0: string, arg1: string | null, arg2: bigint, arg3: Array<LineItem>, arg4: string, arg5: InvoiceType): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n32(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_InvoiceType_n35(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Invoice_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n32(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_InvoiceType_n35(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Invoice_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: CreateUserRequest): Promise<SignUpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(to_candid_CreateUserRequest_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SignUpResponse_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(to_candid_CreateUserRequest_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SignUpResponse_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async editCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCustomer(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCustomer(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async editInvoice(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint, arg4: Array<LineItem>, arg5: InvoiceStatus, arg6: string, arg7: InvoiceType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editInvoice(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_vec_n32(this._uploadFile, this._downloadFile, arg4), to_candid_InvoiceStatus_n44(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_InvoiceType_n35(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editInvoice(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_vec_n32(this._uploadFile, this._downloadFile, arg4), to_candid_InvoiceStatus_n44(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_InvoiceType_n35(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async editItem(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editItem(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editItem(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async fetchGstFilingStatus(arg0: string, arg1: string, arg2: ReturnType_, arg3: FilingFrequency): Promise<GSTFilingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGstFilingStatus(arg0, arg1, to_candid_ReturnType_n46(this._uploadFile, this._downloadFile, arg2), to_candid_FilingFrequency_n48(this._uploadFile, this._downloadFile, arg3));
                return from_candid_GSTFilingStatus_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGstFilingStatus(arg0, arg1, to_candid_ReturnType_n46(this._uploadFile, this._downloadFile, arg2), to_candid_FilingFrequency_n48(this._uploadFile, this._downloadFile, arg3));
            return from_candid_GSTFilingStatus_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async finalizeInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeInvoice(arg0);
            return result;
        }
    }
    async getAccessExpiry(arg0: string): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessExpiry(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessExpiry(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: bigint): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItems();
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItems();
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastSignIn(arg0: string): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastSignIn(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastSignIn(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUsed(arg0: string): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUsed(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUsed(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPotentialSystemRoles(): Promise<Array<SystemRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPotentialSystemRoles();
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPotentialSystemRoles();
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserProfile();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UnifiedUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordInternetIdentitySignIn(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInternetIdentitySignIn();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInternetIdentitySignIn();
            return result;
        }
    }
    async saveBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessProfile(await to_candid_BusinessProfile_n85(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessProfile(await to_candid_BusinessProfile_n85(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAccessExpiry(arg0: string, arg1: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccessExpiry(arg0, to_candid_opt_n90(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccessExpiry(arg0, to_candid_opt_n90(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async signUp(arg0: SignUpRequest): Promise<SignUpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.signUp(to_candid_SignUpRequest_n91(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SignUpResponse_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUp(to_candid_SignUpRequest_n91(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SignUpResponse_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: UpdateUserRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UpdateUserRequest_n93(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UpdateUserRequest_n93(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BankingDetails_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankingDetails): BankingDetails {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
async function from_candid_BusinessProfile_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): Promise<BusinessProfile> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_CredentialResponse_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CredentialResponse): CredentialResponse {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FilingFrequency_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilingFrequency): FilingFrequency {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_GSTFilingStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GSTFilingStatus): GSTFilingStatus {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceType): InvoiceType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LineItem_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LineItem): LineItem {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnType): ReturnType_ {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SignUpResponse_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignUpResponse): SignUpResponse {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_StatusEntry_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusEntry): StatusEntry {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_SystemRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemRole): SystemRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UnifiedUserInfo_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnifiedUserInfo): UnifiedUserInfo {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_UserRecord_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRecord): UserRecord {
    return from_candid_record_n83(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemRole]): SystemRole | null {
    return value.length === 0 ? null : from_candid_SystemRole_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GSTError]): GSTError | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): Promise<BusinessProfile | null> {
    return value.length === 0 ? null : await from_candid_BusinessProfile_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankingDetails]): BankingDetails | null {
    return value.length === 0 ? null : from_candid_BankingDetails_n64(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n67(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: [] | [string];
    billingAddress: string;
    name: string;
    state: string;
    gstin: [] | [string];
}): {
    id: bigint;
    contactInfo?: string;
    billingAddress: string;
    name: string;
    state: string;
    gstin?: string;
} {
    return {
        id: value.id,
        contactInfo: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.contactInfo)),
        billingAddress: value.billingAddress,
        name: value.name,
        state: value.state,
        gstin: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.gstin))
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hsnSac: [] | [string];
    name: string;
    description: [] | [string];
    unitPrice: number;
    defaultGstRate: number;
}): {
    id: bigint;
    hsnSac?: string;
    name: string;
    description?: string;
    unitPrice: number;
    defaultGstRate: number;
} {
    return {
        id: value.id,
        hsnSac: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.hsnSac)),
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.description)),
        unitPrice: value.unitPrice,
        defaultGstRate: value.defaultGstRate
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InvoiceStatus;
    lineItems: Array<_LineItem>;
    purchaseOrderNumber: [] | [string];
    invoiceDate: string;
    invoiceNumber: string;
    invoiceType: _InvoiceType;
    customerId: bigint;
}): {
    id: bigint;
    status: InvoiceStatus;
    lineItems: Array<LineItem>;
    purchaseOrderNumber?: string;
    invoiceDate: string;
    invoiceNumber: string;
    invoiceType: InvoiceType;
    customerId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n17(_uploadFile, _downloadFile, value.status),
        lineItems: from_candid_vec_n19(_uploadFile, _downloadFile, value.lineItems),
        purchaseOrderNumber: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.purchaseOrderNumber)),
        invoiceDate: value.invoiceDate,
        invoiceNumber: value.invoiceNumber,
        invoiceType: from_candid_InvoiceType_n23(_uploadFile, _downloadFile, value.invoiceType),
        customerId: value.customerId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: bigint;
    discount: [] | [number];
    quantity: number;
    unitPrice: number;
}): {
    itemId: bigint;
    discount?: number;
    quantity: number;
    unitPrice: number;
} {
    return {
        itemId: value.itemId,
        discount: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.discount)),
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: [] | [_SystemRole];
    message: string;
    success: boolean;
}): {
    role?: SystemRole;
    message: string;
    success: boolean;
} {
    return {
        role: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.role)),
        message: value.message,
        success: value.success
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    permissions: _Permissions;
    createdAt: bigint;
    role: _SystemRole;
    mobileNumber: string;
    email: string;
    updatedAt: bigint;
    accessExpiry: [] | [_Time];
    lastUsed: [] | [_Time];
}): {
    id: string;
    permissions: Permissions;
    createdAt: bigint;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    updatedAt: bigint;
    accessExpiry?: Time;
    lastUsed?: Time;
} {
    return {
        id: value.id,
        permissions: value.permissions,
        createdAt: value.createdAt,
        role: from_candid_SystemRole_n30(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email,
        updatedAt: value.updatedAt,
        accessExpiry: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.accessExpiry)),
        lastUsed: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastUsed))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    natureOfBusiness: [] | [string];
    tradeName: [] | [string];
    period: string;
    cancellationDate: [] | [string];
    principalPlaceOfBusiness: [] | [string];
    isActive: [] | [boolean];
    filingFrequencyDetails: [] | [string];
    error: [] | [_GSTError];
    legalName: [] | [string];
    statusEntries: Array<_StatusEntry>;
    state: [] | [string];
    gstin: string;
    taxpayerType: [] | [string];
    address: [] | [string];
    gstStatus: [] | [string];
    filingFrequency: _FilingFrequency;
    registrationDate: [] | [string];
    returnType: _ReturnType;
}): {
    natureOfBusiness?: string;
    tradeName?: string;
    period: string;
    cancellationDate?: string;
    principalPlaceOfBusiness?: string;
    isActive?: boolean;
    filingFrequencyDetails?: string;
    error?: GSTError;
    legalName?: string;
    statusEntries: Array<StatusEntry>;
    state?: string;
    gstin: string;
    taxpayerType?: string;
    address?: string;
    gstStatus?: string;
    filingFrequency: FilingFrequency;
    registrationDate?: string;
    returnType: ReturnType_;
} {
    return {
        natureOfBusiness: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.natureOfBusiness)),
        tradeName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.tradeName)),
        period: value.period,
        cancellationDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.cancellationDate)),
        principalPlaceOfBusiness: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.principalPlaceOfBusiness)),
        isActive: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.isActive)),
        filingFrequencyDetails: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.filingFrequencyDetails)),
        error: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.error)),
        legalName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.legalName)),
        statusEntries: from_candid_vec_n53(_uploadFile, _downloadFile, value.statusEntries),
        state: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.state)),
        gstin: value.gstin,
        taxpayerType: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.taxpayerType)),
        address: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.address)),
        gstStatus: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.gstStatus)),
        filingFrequency: from_candid_FilingFrequency_n58(_uploadFile, _downloadFile, value.filingFrequency),
        registrationDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.registrationDate)),
        returnType: from_candid_ReturnType_n56(_uploadFile, _downloadFile, value.returnType)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    periodLabel: string;
    filingDate: [] | [string];
    returnType: _ReturnType;
}): {
    status: string;
    periodLabel: string;
    filingDate?: string;
    returnType: ReturnType_;
} {
    return {
        status: value.status,
        periodLabel: value.periodLabel,
        filingDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.filingDate)),
        returnType: from_candid_ReturnType_n56(_uploadFile, _downloadFile, value.returnType)
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankingDetails: [] | [_BankingDetails];
    startingNumber: bigint;
    logo: [] | [_ExternalBlob];
    businessName: string;
    state: string;
    invoicePrefix: string;
    gstin: string;
    address: string;
}): Promise<{
    bankingDetails?: BankingDetails;
    startingNumber: bigint;
    logo?: ExternalBlob;
    businessName: string;
    state: string;
    invoicePrefix: string;
    gstin: string;
    address: string;
}> {
    return {
        bankingDetails: record_opt_to_undefined(from_candid_opt_n63(_uploadFile, _downloadFile, value.bankingDetails)),
        startingNumber: value.startingNumber,
        logo: record_opt_to_undefined(await from_candid_opt_n66(_uploadFile, _downloadFile, value.logo)),
        businessName: value.businessName,
        state: value.state,
        invoicePrefix: value.invoicePrefix,
        gstin: value.gstin,
        address: value.address
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: [] | [string];
    ifscCode: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
}): {
    branch?: string;
    ifscCode: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
} {
    return {
        branch: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.branch)),
        ifscCode: value.ifscCode,
        bankName: value.bankName,
        accountName: value.accountName,
        accountNumber: value.accountNumber
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        credential: null;
    } | {
        principalOnly: null;
    };
    deleted: [] | [boolean];
    role: [] | [_SystemRole];
    email: [] | [string];
    lastSignIn: [] | [_Time];
    accessExpiry: [] | [_Time];
    identifier: string;
    lastUsed: [] | [_Time];
}): {
    userType: Variant_credential_principalOnly;
    deleted?: boolean;
    role?: SystemRole;
    email?: string;
    lastSignIn?: Time;
    accessExpiry?: Time;
    identifier: string;
    lastUsed?: Time;
} {
    return {
        userType: from_candid_variant_n80(_uploadFile, _downloadFile, value.userType),
        deleted: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.deleted)),
        role: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.role)),
        email: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.email)),
        lastSignIn: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastSignIn)),
        accessExpiry: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.accessExpiry)),
        identifier: value.identifier,
        lastUsed: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastUsed))
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    permissions: _Permissions;
    principal: [] | [Principal];
    deleted: boolean;
    createdAt: bigint;
    role: _SystemRole;
    mobileNumber: string;
    email: string;
    lastSignIn: [] | [_Time];
    updatedAt: bigint;
    accessExpiry: [] | [_Time];
    passwordHash: string;
    lastUsed: [] | [_Time];
}): {
    id: string;
    permissions: Permissions;
    principal?: Principal;
    deleted: boolean;
    createdAt: bigint;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    lastSignIn?: Time;
    updatedAt: bigint;
    accessExpiry?: Time;
    passwordHash: string;
    lastUsed?: Time;
} {
    return {
        id: value.id,
        permissions: value.permissions,
        principal: record_opt_to_undefined(from_candid_opt_n84(_uploadFile, _downloadFile, value.principal)),
        deleted: value.deleted,
        createdAt: value.createdAt,
        role: from_candid_SystemRole_n30(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email,
        lastSignIn: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastSignIn)),
        updatedAt: value.updatedAt,
        accessExpiry: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.accessExpiry)),
        passwordHash: value.passwordHash,
        lastUsed: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastUsed))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    finalized: null;
} | {
    draft: null;
}): InvoiceStatus {
    return "cancelled" in value ? InvoiceStatus.cancelled : "finalized" in value ? InvoiceStatus.finalized : "draft" in value ? InvoiceStatus.draft : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transportation: null;
} | {
    original: null;
}): InvoiceType {
    return "transportation" in value ? InvoiceType.transportation : "original" in value ? InvoiceType.original : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    auditor: null;
} | {
    superAdmin: null;
} | {
    standard: null;
}): SystemRole {
    return "auditor" in value ? SystemRole.auditor : "superAdmin" in value ? SystemRole.superAdmin : "standard" in value ? SystemRole.standard : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstr1: null;
} | {
    gstr3b: null;
}): ReturnType_ {
    return "gstr1" in value ? ReturnType.gstr1 : "gstr3b" in value ? ReturnType.gstr3b : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quarterly: null;
} | {
    monthly: null;
}): FilingFrequency {
    return "quarterly" in value ? FilingFrequency.quarterly : "monthly" in value ? FilingFrequency.monthly : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credential: null;
} | {
    principalOnly: null;
}): Variant_credential_principalOnly {
    return "credential" in value ? Variant_credential_principalOnly.credential : "principalOnly" in value ? Variant_credential_principalOnly.principalOnly : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LineItem>): Array<LineItem> {
    return value.map((x)=>from_candid_LineItem_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusEntry>): Array<StatusEntry> {
    return value.map((x)=>from_candid_StatusEntry_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SystemRole>): Array<SystemRole> {
    return value.map((x)=>from_candid_SystemRole_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UnifiedUserInfo>): Array<UnifiedUserInfo> {
    return value.map((x)=>from_candid_UnifiedUserInfo_n78(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRecord>): Array<UserRecord> {
    return value.map((x)=>from_candid_UserRecord_n82(_uploadFile, _downloadFile, x));
}
function to_candid_BankingDetails_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankingDetails): _BankingDetails {
    return to_candid_record_n88(_uploadFile, _downloadFile, value);
}
async function to_candid_BusinessProfile_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): Promise<_BusinessProfile> {
    return await to_candid_record_n86(_uploadFile, _downloadFile, value);
}
function to_candid_CreateUserRequest_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateUserRequest): _CreateUserRequest {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FilingFrequency_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilingFrequency): _FilingFrequency {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): _InvoiceType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_LineItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineItem): _LineItem {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ReturnType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnType_): _ReturnType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_SignUpRequest_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignUpRequest): _SignUpRequest {
    return to_candid_record_n92(_uploadFile, _downloadFile, value);
}
function to_candid_SystemRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemRole): _SystemRole {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserRequest_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserRequest): _UpdateUserRequest {
    return to_candid_record_n94(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: bigint;
    discount?: number;
    quantity: number;
    unitPrice: number;
}): {
    itemId: bigint;
    discount: [] | [number];
    quantity: number;
    unitPrice: number;
} {
    return {
        itemId: value.itemId,
        discount: value.discount ? candid_some(value.discount) : candid_none(),
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}): {
    password: string;
    role: _SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry: [] | [_Time];
} {
    return {
        password: value.password,
        role: to_candid_SystemRole_n39(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email,
        accessExpiry: value.accessExpiry ? candid_some(value.accessExpiry) : candid_none()
    };
}
async function to_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankingDetails?: BankingDetails;
    startingNumber: bigint;
    logo?: ExternalBlob;
    businessName: string;
    state: string;
    invoicePrefix: string;
    gstin: string;
    address: string;
}): Promise<{
    bankingDetails: [] | [_BankingDetails];
    startingNumber: bigint;
    logo: [] | [_ExternalBlob];
    businessName: string;
    state: string;
    invoicePrefix: string;
    gstin: string;
    address: string;
}> {
    return {
        bankingDetails: value.bankingDetails ? candid_some(to_candid_BankingDetails_n87(_uploadFile, _downloadFile, value.bankingDetails)) : candid_none(),
        startingNumber: value.startingNumber,
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n89(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        businessName: value.businessName,
        state: value.state,
        invoicePrefix: value.invoicePrefix,
        gstin: value.gstin,
        address: value.address
    };
}
function to_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch?: string;
    ifscCode: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
}): {
    branch: [] | [string];
    ifscCode: string;
    bankName: string;
    accountName: string;
    accountNumber: string;
} {
    return {
        branch: value.branch ? candid_some(value.branch) : candid_none(),
        ifscCode: value.ifscCode,
        bankName: value.bankName,
        accountName: value.accountName,
        accountNumber: value.accountNumber
    };
}
function to_candid_record_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}): {
    password: string;
    mobileNumber: string;
    email: string;
    accessExpiry: [] | [_Time];
} {
    return {
        password: value.password,
        mobileNumber: value.mobileNumber,
        email: value.email,
        accessExpiry: value.accessExpiry ? candid_some(value.accessExpiry) : candid_none()
    };
}
function to_candid_record_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Permissions;
    role: SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry?: Time;
}): {
    permissions: _Permissions;
    role: _SystemRole;
    mobileNumber: string;
    email: string;
    accessExpiry: [] | [_Time];
} {
    return {
        permissions: value.permissions,
        role: to_candid_SystemRole_n39(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber,
        email: value.email,
        accessExpiry: value.accessExpiry ? candid_some(value.accessExpiry) : candid_none()
    };
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): {
    transportation: null;
} | {
    original: null;
} {
    return value == InvoiceType.transportation ? {
        transportation: null
    } : value == InvoiceType.original ? {
        original: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemRole): {
    auditor: null;
} | {
    superAdmin: null;
} | {
    standard: null;
} {
    return value == SystemRole.auditor ? {
        auditor: null
    } : value == SystemRole.superAdmin ? {
        superAdmin: null
    } : value == SystemRole.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    cancelled: null;
} | {
    finalized: null;
} | {
    draft: null;
} {
    return value == InvoiceStatus.cancelled ? {
        cancelled: null
    } : value == InvoiceStatus.finalized ? {
        finalized: null
    } : value == InvoiceStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnType_): {
    gstr1: null;
} | {
    gstr3b: null;
} {
    return value == ReturnType.gstr1 ? {
        gstr1: null
    } : value == ReturnType.gstr3b ? {
        gstr3b: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilingFrequency): {
    quarterly: null;
} | {
    monthly: null;
} {
    return value == FilingFrequency.quarterly ? {
        quarterly: null
    } : value == FilingFrequency.monthly ? {
        monthly: null
    } : value;
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LineItem>): Array<_LineItem> {
    return value.map((x)=>to_candid_LineItem_n33(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
